#!/bin/bash

#
## SCRIPT HECHO POR Oscar Montero - Adaptado para Python 3.11.9
### Script de instalación de Odoo, PostgreSQL, Nginx, Firewall y Certbot.
# ODOO_VERSION="17.0"
# POSTGRESQL_VERSION="13"
# Python_version="3.11.9"
#

# Actualizar el sistema
sudo dnf install epel-release dnf-plugins-core -y

# Instalar NGINX y Certbot
sudo dnf install -y certbot nginx

# Crear carpetas de configuración NGINX
sudo mkdir -p /etc/nginx/sites-available /etc/nginx/sites-enabled

# Reemplazar nginx.conf
sudo rm -f /etc/nginx/nginx.conf
sudo sh -c "cat << 'EOF' > /etc/nginx/nginx.conf
# For more information on configuration, see:
# * Official English Documentation: http://nginx.org/en/docs/
# * Official Russian Documentation: http://nginx.org/ru/docs/
user nginx;
worker_processes auto;
error_log /var/log/nginx/error.log;
pid /run/nginx.pid;

# Load dynamic modules. See /usr/share/doc/nginx/README.dynamic.
include /usr/share/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    log_format main '\$remote_addr - \$remote_user [\$time_local] "\$request" '
        '\$status \$body_bytes_sent "\$http_referer" '
        '"\$http_user_agent" "\$http_x_forwarded_for"';
    access_log /var/log/nginx/access.log main;

    sendfile on;
    tcp_nopush on;
    tcp_nodelay on;
    keepalive_timeout 65;
    types_hash_max_size 2048;

    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;
    include /etc/nginx/sites-enabled/*.conf;
}
EOF"

# Crear archivo dhparam.pem
sudo mkdir -p /etc/cert/certs
sudo sh -c 'cat <<EOF > /etc/cert/certs/dhparam.pem
-----BEGIN DH PARAMETERS-----
MIICCAKCAgEA3eINXN1xzhfnc7ku6Vuim65H0K+kjZD9yiKVLTBw41EYJVfRupOX
ze05bzJFQlLipBiI9OAOWuiwLLkFeGxu3fFkOVfaviR5VBpPz6sQYwNL152Fs37y
j74Y8orq01sgn+BB++S0CIQCh+AQWzSjyEnGuME93wH2NBMl52Ht9ZWmFSn6XvQM
Tvx5vpBNk/4+i5NPZ6Ptc6jH1lofXh/0F1Yvg0yUyhYJzzwJUNrRju5V0y4qS3Y1
HiU267HEd7T1zuc20Yl+/Rs8lULe6+kS77Y3+5u1hozen4WcM2rIxGEBCBCDjNf9
km5wP1HHhnq/KZtlv0u68wEW73AO5zWzLRI2KaclS0X2c4zMkvM3q1BlE1ZSctq6
lR08sR3zCENrpLqtRL4+0HWNxUEBAPjq/4jyacmbFsQ/59D9dCiJt/hLehG3O8P1
OYRWqCMuOQT4T78wQQcTZHxguxdaUdxmgfNBP0SXfjeebApgpg8YhtgD1biGYFqc
lCHvoHALCBwvQWgu5lCd+RuBqPXRTC27fy9xpo1js9+KzJpxIluqodDBGlX88VYJ
ZkGswo0RIqst5AbE8w9Dq3lEmPH3Y68ViFzvbFtePFx9NdxvTjLhMNzvZvQGgWJI
eeXdqk+M3lfk6Rmy+LrqUiru/fPbPNPLyAFBByTmYf8OMQA/cOiKrAMCAQI=
-----END DH PARAMETERS-----
EOF'

# Configuración del sitio Odoo en NGINX
sudo sh -c 'cat <<EOF > /etc/nginx/sites-available/odoo.conf
limit_req_zone \$binary_remote_addr zone=ip:10m rate=3r/s;

upstream odoo {
    server 127.0.0.1:8069;
}

upstream odoo-chat {
    server 127.0.0.1:8072;
}

server {
    listen 80;
    server_name <nombre_dns_servidor>;

    limit_req zone=ip burst=60;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl http2;
    server_name <nombre_dns_servidor>;

    # SSL
    ssl_certificate /etc/letsencrypt/live/<nombre_dns_servidor>/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/<nombre_dns_servidor>/privkey.pem;
    ssl_trusted_certificate /etc/letsencrypt/live/<nombre_dns_servidor>/chain.pem;

    ssl_stapling on;
    ssl_stapling_verify on;

    ssl_session_timeout 1d;
    ssl_session_cache shared:SSL:50m;
    ssl_session_tickets off;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    add_header Strict-Transport-Security "max-age=15768000" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "no-referrer-when-downgrade" always;

    resolver 8.8.8.8 8.8.4.4;

    access_log /var/log/nginx/odoo.access.log;
    error_log /var/log/nginx/odoo.error.log;

    client_max_body_size 256M;

    proxy_read_timeout 720s;
    proxy_connect_timeout 720s;
    proxy_send_timeout 720s;

    proxy_set_header Host \$host;
    proxy_set_header X-Real-IP \$remote_addr;
    proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;

    # Odoo principal
    location / {
        proxy_pass http://odoo;
        proxy_redirect off;
    }

    # Chat Odoo - WebSocket
    location /websocket {
        proxy_pass http://odoo-chat;
        proxy_http_version 1.1;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_read_timeout 86400s;
        proxy_send_timeout 86400s;
    }

    # Longpolling (fallback)
    location /longpolling/ {
        proxy_pass http://odoo-chat;
        proxy_http_version 1.1;

        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;
    }

    # Assets sin cache
    location ~* /web/static/ {
        proxy_pass http://odoo;
        add_header Cache-Control "no-store";
    }

    gzip on;
    gzip_types text/css text/less text/plain text/xml application/xml application/json application/javascript;
}
EOF'

# Activar el sitio de Odoo en NGINX
sudo ln -s /etc/nginx/sites-available/odoo.conf /etc/nginx/sites-enabled/odoo.conf
sudo systemctl enable nginx
sudo setsebool -P nis_enabled 1

# Dependencias del sistema
sudo dnf install -y git gcc wget nodejs libxslt-devel bzip2-devel openldap-devel libjpeg-devel freetype-devel postgresql-libs postgresql-devel gcc-c++ epel-release
sudo dnf install -y python3-devel libsasl2-devel openldap-devel

# Instalar Python 3.11.9 desde fuente
PYTHON_VERSION="3.11.9"
cd /usr/src
sudo dnf groupinstall "Development Tools" -y
sudo dnf install -y gcc gcc-c++ make zlib-devel bzip2 bzip2-devel readline-devel sqlite sqlite-devel openssl-devel xz xz-devel libffi-devel tar
sudo wget https://www.python.org/ftp/python/${PYTHON_VERSION}/Python-${PYTHON_VERSION}.tgz
sudo tar xvf Python-${PYTHON_VERSION}.tgz
cd Python-${PYTHON_VERSION}
sudo ./configure --enable-optimizations --prefix=/usr/local
sudo make -j$(nproc)
sudo make altinstall
cd ~

# Instalar wkhtmltopdf
sudo mkdir -p /opt/odoo/
sudo wget -P /opt/odoo https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox-0.12.6.1-2.almalinux9.x86_64.rpm
sudo dnf localinstall -y /opt/odoo/wkhtmltox-0.12.6.1-2.almalinux9.x86_64.rpm

# Instalar PostgreSQL 13
sudo dnf install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
sudo dnf config-manager --set-disabled pgdg16
sudo dnf -qy module disable postgresql
sudo dnf install -y postgresql13-server postgresql13 postgresql13-devel --nobest --skip-broken
sudo /usr/pgsql-13/bin/postgresql-13-setup initdb
sudo systemctl start postgresql-13
sudo systemctl enable postgresql-13
sudo su - postgres -c "createuser -s odoo"

# Crear usuario Odoo y entorno virtual
sudo useradd -m -U -r -d /opt/odoo -s /bin/bash odoo
sudo chown -R odoo /opt/odoo
sudo su - odoo -c "git clone https://www.github.com/odoo/odoo --depth 1 --branch 17.0 /opt/odoo/odoo17"
sudo su - odoo -c "/usr/local/bin/python3.11 -m venv /opt/odoo/odoo17-venv"
sudo su - odoo -c "source /opt/odoo/odoo17-venv/bin/activate && pip install --upgrade pip && pip install -r /opt/odoo/odoo17/requirements.txt && pip install psycopg2-binary && pip install google_auth && deactivate"
sudo su - odoo -c "mkdir /opt/odoo/odoo17-custom-addons"

# Logs
sudo mkdir /var/log/odoo17
sudo touch /var/log/odoo17/odoo.log
sudo chown -R odoo:odoo /var/log/odoo17
sudo chmod -R 755 /var/log/odoo17/

# Configuración Odoo
sudo sh -c 'cat <<EOF > /etc/odoo.conf
[options]
admin_passwd = Iedoo8oo ohPii4ai
db_host = False
db_port = False
db_user = odoo
db_password = False
xmlrpc_port = 8069
longpolling_port = 8072
logfile = /var/log/odoo17/odoo.log
logrotate = True
addons_path = /opt/odoo/odoo17/addons,/opt/odoo/odoo17-custom-addons
proxy_mode = True
workers = 3
limit_memory_soft = 1374405120
limit_memory_hard = 1595864371
limit_time_cpu = 60
limit_time_real = 120
max_cron_threads = 1
EOF'

# Servicio systemd
sudo sh -c 'cat <<EOF > /etc/systemd/system/odoo17.service
[Unit]
Description=Odoo17
StartLimitIntervalSec=300
StartLimitBurst=5
[Service]
Type=simple
SyslogIdentifier=odoo17
PermissionsStartOnly=true
User=odoo
Group=odoo
ExecStart=/opt/odoo/odoo17-venv/bin/python3.11 /opt/odoo/odoo17/odoo-bin -c /etc/odoo.conf
StandardOutput=journal+console
Restart=on-failure
RestartSec=1s
[Install]
WantedBy=multi-user.target
EOF'

# Activar servicio
sudo systemctl daemon-reload
sudo systemctl start odoo17
sudo systemctl enable odoo17

# Firewalld
sudo dnf install -y firewalld
sudo systemctl start firewalld
sudo systemctl enable firewalld
sudo firewall-cmd --add-port=80/tcp --permanent
sudo firewall-cmd --add-port=443/tcp --permanent
sudo firewall-cmd --add-port=8888/tcp --permanent
sudo firewall-cmd --reload

# Memoria Swap
sudo fallocate -l 2G /swapfile
sudo chmod 600 /swapfile
sudo mkswap /swapfile
sudo swapon /swapfile
echo '/swapfile none swap sw 0 0' | sudo tee -a /etc/fstab

# Permisos finales
sudo chown -R odoo:odoo /opt/odoo
sudo chmod -R 755 /opt/odoo
sudo reboot
